
name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        path: ~/.ansible/roles/geant4
    - name: Run install.yml
      run: ansible-playbook  ~/.ansible/roles/geant4/tests/test.yml
