
name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: ansible-galaxy install git+https://github.com/jw3126/ansible-role-geant4.git
    - uses: actions/checkout@v2
    - name: playbook
      run: ansible-playbook --become tests/test.yml
